### ISSUE TITLE
It says I live in the woods but I live right outside of Seattle

### ISSUE THREAD

**Issue by hailstotheyeah** [Bulbacode/fucking-famished#12]
When I put in my location (I live in Bellevue, WA) and have my radius all the way to 50 miles it says I live in the woods. I would love this app to work for me because idk what to get for dinner lol 
![D2D9CD8E-1FD7-4A33-ACE8-2F598C09FE13](https://user-images.githubusercontent.com/77992974/105760862-3267b800-5f07-11eb-85f6-7e9c92fa6b9f.png)

**Comment by Bulbacode** [comment]
Known bug related to most recent release.
