### ISSUE TITLE
Won’t show me a restaurant 

### ISSUE THREAD

**Issue by fartasf** [Bulbacode/fucking-famished#15]
I live in downtown Atlanta and it said theres no places near me even after I put the distance at max. 
![98891C81-8A84-4F8C-BB03-BB93D9137D25](https://user-images.githubusercontent.com/77998076/105775161-5c839f00-5f34-11eb-8701-411f861f9375.png)

**Comment by Bulbacode** [comment]
Closing as duplicate of #14
