### ISSUE TITLE
As much as one may like to eat ass...

### ISSUE THREAD

**Issue by thiccxdaddy** [Bulbacode/fucking-famished#6]
![12949D24-9626-47F9-AA2C-1D8F09741087](https://user-images.githubusercontent.com/77951364/105662342-baf54280-5e8c-11eb-9c41-2d48efd5b61f.png)

I think this took things to an extreme. Who am I to say this is completely wrong, they may have good wings but not somewhere to take the whole family. 

Also would like to say it also offered me a casino and ballroom... only actual food place was subway. 🤮

would be kind of cool if you had an option for price range.

**Comment by Bulbacode** [comment]
I'm assuming this is one of the strip clubs?
@thiccxdaddy

**Comment by thiccxdaddy** [comment]
> I'm assuming this is one of the strip clubs?
> @thiccxdaddy

Yes it is

**Comment by Bulbacode** [comment]
Lumping this in with #4
